import React,{useEffect,useMemo,useState}from"react";
import{BookOpen,Brain,CalendarDays,Check,ChevronRight,CircleUserRound,Flame,Headphones,Home,Keyboard,Languages,LogIn,LogOut,Menu,Mic,Play,RotateCcw,Settings,ShieldCheck,Sparkles,Star,Target,Trophy,Volume2,X,BarChart3,Clock3,Lock,CheckCircle2,ArrowLeft,RefreshCw}from"lucide-react";
import{week1,dayToLesson}from"./data/week1.js";
import{watchAuth,loginWithEmail,registerWithEmail,logout,loadProgress,saveProgress,saveAttempt,loadLesson}from"./lib/firebase.js";
import{speak,listenOnce,similarity,speechRecognitionSupported}from"./lib/speech.js";

const HIRA=[["あ","a"],["い","i"],["う","u"],["え","e"],["お","o"],["か","ka"],["き","ki"],["く","ku"],["け","ke"],["こ","ko"],["さ","sa"],["し","shi"],["す","su"],["せ","se"],["そ","so"],["た","ta"],["ち","chi"],["つ","tsu"],["て","te"],["と","to"],["な","na"],["に","ni"],["ぬ","nu"],["ね","ne"],["の","no"],["は","ha"],["ひ","hi"],["ふ","fu"],["へ","he"],["ほ","ho"],["ま","ma"],["み","mi"],["む","mu"],["め","me"],["も","mo"],["や","ya"],["ゆ","yu"],["よ","yo"],["ら","ra"],["り","ri"],["る","ru"],["れ","re"],["ろ","ro"],["わ","wa"],["を","o"],["ん","n"]];
const KATA=[["ア","a"],["イ","i"],["ウ","u"],["エ","e"],["オ","o"],["カ","ka"],["キ","ki"],["ク","ku"],["ケ","ke"],["コ","ko"],["サ","sa"],["シ","shi"],["ス","su"],["セ","se"],["ソ","so"],["タ","ta"],["チ","chi"],["ツ","tsu"],["テ","te"],["ト","to"],["ナ","na"],["ニ","ni"],["ヌ","nu"],["ネ","ne"],["ノ","no"],["ハ","ha"],["ヒ","hi"],["フ","fu"],["ヘ","he"],["ホ","ho"],["マ","ma"],["ミ","mi"],["ム","mu"],["メ","me"],["モ","mo"],["ヤ","ya"],["ユ","yu"],["ヨ","yo"],["ラ","ra"],["リ","ri"],["ル","ru"],["レ","re"],["ロ","ro"],["ワ","wa"],["ヲ","o"],["ン","n"]];
const KANJI=[["日","にち / ひ","day / sun"],["月","げつ / つき","month / moon"],["火","か / ひ","fire"],["水","すい / みず","water"],["木","もく / き","tree"],["金","きん / かね","gold / money"],["土","ど / つち","earth"],["人","じん / ひと","person"],["一","いち / ひと","one"],["二","に / ふた","two"],["三","さん / み","three"],["四","し / よん","four"],["五","ご / いつ","five"],["六","ろく / む","six"],["七","しち / なな","seven"],["八","はち / や","eight"],["九","きゅう / ここの","nine"],["十","じゅう / とお","ten"],["学","がく / まな","study"],["校","こう","school"],["生","せい / い","life / student"],["先","せん / さき","previous / ahead"],["本","ほん / もと","book / origin"],["語","ご / かた","language"],["食","しょく / た","eat / food"],["飲","いん / の","drink"],["見","けん / み","see"],["行","こう / い","go"],["来","らい / く","come"],["大","だい / おお","big"],["小","しょう / ちい","small"]];

const fallbackVocab=[["こんにちは","konnichiwa","hello"],["ありがとう","arigatō","thank you"],["すみません","sumimasen","excuse me"],["わたし","watashi","I"],["ともだち","tomodachi","friend"],["せんせい","sensei","teacher"],["がくせい","gakusei","student"],["ほん","hon","book"],["みず","mizu","water"],["がっこう","gakkō","school"],["えき","eki","station"],["でんしゃ","densha","train"],["たべます","tabemasu","eat"],["のみます","nomimasu","drink"],["みます","mimasu","watch"],["よみます","yomimasu","read"],["いきます","ikimasu","go"],["すき","suki","like"],["おおきい","ōkii","big"],["ちいさい","chiisai","small"]];
const grammar=[["N は N です","Topic + polite identity","は establishes the topic and です makes a polite statement."],["N の N","Possession / relationship","の links nouns: a person's book, school teacher, and similar relationships."],["N も N です","Also / too","も replaces は when adding another item with the same predicate."],["N を Vます","Direct object","を marks the direct object of a transitive verb."],["Place に いきます","Destination","に marks a destination with movement verbs."],["N が すきです","Like","が marks the thing liked with すきです."]];
const daysBetween=(a,b)=>Math.floor((new Date(b+"T00:00:00")-new Date(a+"T00:00:00"))/86400000);
function makeQuiz(vs){return vs.slice(0,10).map((v,i)=>({question:"What does "+v.ja+" mean?",options:[v.en,vs[(i+1)%vs.length].en,vs[(i+2)%vs.length].en,vs[(i+3)%vs.length].en],answer:0}))}
function fallbackLesson(day){
 const level=day<=90?"N5":"N4",local=day<=90?day:day-90,g=grammar[(local-1)%grammar.length],start=((local-1)*4)%fallbackVocab.length;
 const vs=Array.from({length:12},(_,i)=>fallbackVocab[(start+i)%fallbackVocab.length]).map(v=>({ja:v[0],romaji:v[1],en:v[2]}));
 const ex=vs.slice(0,3).map(v=>({ja:v.ja+"。",romaji:v.romaji+" desu.",en:"Practice "+v.en+" in context."}));
 return{day,level,title:level+" Day "+local+" · "+g[0],theme:"Core Japanese · "+g[1],characters:[],kanji:KANJI.slice((local-1)%20,(local-1)%20+5).map(k=>({character:k[0],reading:k[1],meaning:k[2]})),vocab:vs,grammar:[{pattern:g[0],meaning:g[1],explanation:g[2]}],examples:ex,speaking:ex.map(x=>x.ja),reading:{text:ex.map(x=>x.ja).join(""),translation:"Read aloud twice. Then explain the meaning without looking at English."},listening:{script:ex[0].ja,prompt:"Listen without looking, repeat, then write what you heard."},quiz:makeQuiz(vs),review:{spacedReviewDays:[1,3,7,14,30],recallPrompt:"Recall five vocabulary items and today's grammar pattern without looking."},objectives:["Recognize today's vocabulary","Understand the grammar pattern","Shadow Japanese aloud","Read the example text","Score 100% on the mastery check"]};
}
function normalizeLesson(raw,day){
 if(!raw)return fallbackLesson(day);
 const vocab=(raw.vocab||[]).map(v=>Array.isArray(v)?{ja:v[0],romaji:v[1],en:v[2]}:v);
 const grammar=(raw.grammar||[]).map(g=>Array.isArray(g)?{pattern:g[0],meaning:g[1],explanation:g[2]}:g);
 const examples=(raw.examples||[]).map(e=>Array.isArray(e)?{ja:e[0],romaji:e[1],en:e[2]}:e);
 const chars=(raw.characters||[]).map(c=>Array.isArray(c)?{script:c[0],romaji:c[1],meaning:"Japanese character"}:c);
 return{...raw,day:raw.day||day,vocab,grammar,examples,characters:chars,kanji:raw.kanji||[],speaking:Array.isArray(raw.speaking)?raw.speaking:(raw.speaking?.shadowing||examples.map(e=>e.ja)),reading:raw.reading||{text:examples.map(e=>e.ja).join(" "),translation:examples.map(e=>e.en).join(" ")},listening:raw.listening||{script:examples[0]?.ja||"",prompt:"Listen, repeat and write what you hear."},quiz:raw.quiz?.length?raw.quiz:makeQuiz(vocab),objectives:raw.objectives||["Learn the day's vocabulary","Understand the grammar","Speak the examples aloud","Complete the mastery check"]};
}
function localLesson(day){return day<=7?normalizeLesson(dayToLesson(week1[day-1]),day):fallbackLesson(day)}
function getStreak(){try{return JSON.parse(localStorage.getItem("michiActivity")||"[]")}catch{return[]}}
function markActivity(){const today=new Date().toISOString().slice(0,10),a=getStreak();if(!a.includes(today)){a.push(today);localStorage.setItem("michiActivity",JSON.stringify(a.slice(-120)))}return a}
function calcStreak(a){const s=new Set(a),today=new Date(),base=new Date(today);let count=0;for(let i=0;i<365;i++){const d=new Date(base);d.setDate(base.getDate()-i);if(s.has(d.toISOString().slice(0,10)))count++;else if(i>0)break}return count}
function pct(a,b){return b?Math.round(a/b*100):0}

function AuthModal({mode,setMode,onClose}){
 const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(e){e.preventDefault();setError("");setBusy(true);try{if(mode==="register")await registerWithEmail(email,password);else await loginWithEmail(email,password);onClose()}catch(err){setError(err?.message||"Authentication failed.")}finally{setBusy(false)}}
 return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="auth-card" onSubmit={submit}><div className="auth-brand"><div className="logo-mark">道</div><div><b>Michi <span>みち</span></b><small>Your path to Japanese</small></div><button type="button" className="icon-btn" onClick={onClose}><X size={17}/></button></div><span className="eyebrow">{mode==="login"?"WELCOME BACK":"START YOUR JOURNEY"}</span><h2>{mode==="login"?"Continue your Japanese journey":"Create your Michi account"}</h2><p>Sync your mastery, streaks and learning history across devices.</p><label className="field-label">Email<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="you@example.com"/></label><label className="field-label">Password<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required minLength={6} placeholder="At least 6 characters"/></label>{error&&<div className="error-box">{error}</div>}<button className="btn primary wide" disabled={busy}>{busy?"Please wait…":mode==="login"?"Sign in":"Create account"}</button><div className="auth-switch">{mode==="login"?"New to Michi?":"Already have an account?"}<button type="button" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"Create an account":"Sign in"}</button></div></form></div>
}

function Tutor(){return <div className="tutor"><div className="tutor-glow"/><div className="tutor-copy"><span className="pill violet">Michi Tutor</span><h3>いっしょに勉強しましょう。</h3><p>Listen. Repeat. Understand. Use it.</p></div><div className="tutor-avatar"><div className="tutor-face"><i/><i/></div><div className="tutor-shirt"/></div></div>}
function Audio({text}){return <button className="icon-btn audio" onClick={()=>speak(text)} title="Play Japanese"><Volume2 size={15}/></button>}
function Stat({icon,value,label,trend}){return <div className="stat"><div className="stat-icon">{icon}</div><div><strong>{value}</strong><span>{label}</span>{trend&&<em>{trend}</em>}</div></div>}

function Lesson({lesson,day,onBack,onComplete}){
 const[stage,setStage]=useState("overview"),[attempt,setAttempt]=useState(null),[speaking,setSpeaking]=useState(false),[heard,setHeard]=useState(""),[speakScore,setSpeakScore]=useState(null);
 const stages=[["overview","Overview"],["letters","Letters"],["vocab","Vocabulary"],["grammar","Grammar"],["listen","Listening"],["speak","Speaking"],["read","Reading"],["kanji","Kanji"],["quiz","Mastery"]];
 const target=lesson.examples?.[0]?.ja||lesson.speaking?.[0]||"こんにちは。";
 function runSpeak(){setSpeaking(true);setHeard("");setSpeakScore(null);listenOnce({onResult:t=>{setHeard(t);setSpeakScore(Math.round(similarity(t,target)*100));},onError:e=>setHeard(e==="not-allowed"?"Microphone permission was denied.":"Speech recognition error."),onEnd:()=>setSpeaking(false)})}
 return <div className="fade-in"><button className="back-link" onClick={onBack}><ArrowLeft size={14}/> Back to dashboard</button><div className="lesson-hero"><div><span className="pill violet">{lesson.level} · DAY {day}</span><h1>{lesson.title}</h1><p>{lesson.theme}</p></div><div className="lesson-actions"><button className="btn ghost" onClick={()=>speak(target)}><Volume2 size={15}/> Listen</button><button className="btn primary" onClick={()=>setStage("quiz")}><Target size={15}/> Take mastery quiz</button></div></div>
 <div className="lesson-nav">{stages.map(([id,name],i)=><button key={id} className={stage===id?"active":""} onClick={()=>setStage(id)}><span>{i+1}</span>{name}</button>)}</div>
 {stage==="overview"&&<div className="lesson-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">TODAY'S OBJECTIVES</span><h2>Build one complete skill loop</h2></div><Sparkles size={20}/></div><div className="objective-list">{lesson.objectives.map((o,i)=><div key={o}><CheckCircle2 size={17}/><span>{o}</span></div>)}</div><div className="callout"><Headphones size={18}/><div><b>Recommended order</b><p>Vocabulary → Grammar → Listen → Speak → Read → Quiz</p></div></div></section><aside><Tutor/><div className="panel compact-panel"><span className="eyebrow">SPACED REVIEW</span><h3>Recall again later</h3><p>Review this lesson after 1, 3, 7, 14 and 30 days.</p><div className="review-dots">{[1,3,7,14,30].map(x=><span key={x}>{x}d</span>)}</div></div></aside></div>}
 {stage==="letters"&&<LettersPanel lesson={lesson}/>}
 {stage==="vocab"&&<section className="panel"><div className="panel-head"><div><span className="eyebrow">ACTIVE RECALL</span><h2>{lesson.vocab.length} vocabulary items</h2></div><span className="pill">{lesson.level}</span></div><div className="word-grid">{lesson.vocab.map(v=><div className="word-card" key={v.ja}><div><strong>{v.ja}</strong><small>{v.romaji}</small><span>{v.en}</span></div><Audio text={v.ja}/></div>)}</div></section>}
 {stage==="grammar"&&<section className="panel"><span className="eyebrow">GRAMMAR</span><h2>Understand the pattern</h2>{lesson.grammar.map((g,i)=><div className="grammar-card" key={g.pattern}><div className="grammar-number">{String(i+1).padStart(2,"0")}</div><div><h3>{g.pattern}</h3><b>{g.meaning}</b><p>{g.explanation}</p></div></div>)}<div className="examples"><h3>Examples</h3>{lesson.examples.map(e=><div className="example" key={e.ja}><div><strong>{e.ja}</strong><small>{e.romaji}</small><span>{e.en}</span></div><Audio text={e.ja}/></div>)}</div></section>}
 {stage==="listen"&&<section className="panel"><span className="eyebrow">LISTENING LAB</span><h2>Train your ear</h2><p className="muted">{lesson.listening?.prompt}</p><div className="listen-card"><button className="play-big" onClick={()=>speak(lesson.listening?.script||target)}><Play size={22}/></button><div><span className="eyebrow">JAPANESE AUDIO</span><h3>{lesson.listening?.script||target}</h3><p>Listen 3×. First with text, then without text.</p></div></div><div className="dictation"><span className="eyebrow">DICTATION</span><h3>What did you hear?</h3><input placeholder="Type the Japanese you heard…" onChange={e=>setAttempt(e.target.value)}/><button className="btn primary" onClick={()=>setAttempt(attempt===lesson.listening?.script?"✓ Correct":"Try again")}>Check answer</button>{attempt&&<p className={attempt==="✓ Correct"?"success":"muted"}>{attempt}</p>}</div></section>}
 {stage==="speak"&&<section className="panel"><span className="eyebrow">SPEAKING LAB</span><h2>Say it yourself</h2><p className="muted">The browser listens to your Japanese and estimates how closely it matches the target. Accuracy depends on your microphone and browser.</p><div className="speak-target"><div><span className="eyebrow">TARGET</span><strong>{target}</strong></div><Audio text={target}/></div><button className={"speak-button "+(speaking?"recording":"")} onClick={runSpeak}><Mic size={25}/>{speaking?"Listening…":"Start speaking"}</button>{heard&&<div className="speech-result"><span>You said</span><strong>{heard}</strong>{speakScore!==null&&<em>{speakScore}% match</em>}</div>}{!speechRecognitionSupported()&&<div className="callout warning"><Mic size={16}/><span>This browser does not expose speech recognition. Japanese audio playback still works.</span></div>}</section>}
 {stage==="read"&&<section className="panel"><span className="eyebrow">READING LAB</span><h2>Read for meaning</h2><div className="reading-card"><div>{lesson.reading?.text}</div><small>{lesson.reading?.translation}</small></div><div className="reading-tasks"><div><b>1</b><span>Read silently once.</span></div><div><b>2</b><span>Read aloud twice.</span></div><div><b>3</b><span>Explain the sentence without looking at English.</span></div></div></section>}
 {stage==="kanji"&&<section className="panel"><span className="eyebrow">KANJI LAB</span><h2>Character recognition</h2><div className="kanji-grid">{(lesson.kanji?.length?lesson.kanji:KANJI.slice((day-1)%15,(day-1)%15+6).map(k=>({character:k[0],reading:k[1],meaning:k[2]}))).map(k=><div className="kanji-card" key={k.character}><strong>{k.character}</strong><span>{k.reading}</span><small>{k.meaning}</small><button onClick={()=>speak(k.character)}><Volume2 size={14}/></button></div>)}</div></section>}
 {stage==="quiz"&&<MasteryQuiz lesson={lesson} onComplete={onComplete}/>}
 </div>
}

function LettersPanel({lesson}){
 const letters=lesson.letters||{newLetters:[],reviewLetters:[],cumulativeMasteredCount:0,phase:"Script Foundation",target:"Learn today's Japanese letters.",masteryChecks:[]};
 const pool=letters.newLetters?.length?letters.newLetters:letters.reviewLetters||[];
 const[item,setItem]=useState(pool[0]||null),[answer,setAnswer]=useState(""),[score,setScore]=useState(0),[attempts,setAttempts]=useState(0);
 useEffect(()=>{setItem(pool[0]||null);setAnswer("");setScore(0);setAttempts(0)},[lesson.day]);
 function check(){if(!item)return;const ok=answer.trim().toLowerCase()===item.romaji.toLowerCase();setAttempts(attempts+1);if(ok)setScore(score+1);const next=pool[(pool.indexOf(item)+1)%Math.max(1,pool.length)];setTimeout(()=>{setItem(next);setAnswer("")},300)}
 return <section className="letters-panel">
   <div className="letters-header"><div><span className="eyebrow">LETTERS TO LEARN TODAY</span><h2>{letters.phase}</h2><p>{letters.target}</p></div><div className="letters-count"><strong>{letters.cumulativeMasteredCount}</strong><span>script items<br/>in your bank</span></div></div>
   <div className="letter-learning-grid">
    <div className="letter-trainer">
      <span className="eyebrow">RECOGNITION PRACTICE</span>
      {item?<><div className="letter-big">{item.char}</div><div className="letter-type">{item.type} · say it aloud</div><Audio text={item.char}/><input value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>e.key==="Enter"&&check()} placeholder="Type the romaji sound…" /><button className="btn primary wide" onClick={check}>Check letter</button><small>{score} correct · {attempts} attempts</small></>:<p className="muted">Today's set is a mastery/review day. Use the review grid below.</p>}
    </div>
    <div>
      <span className="eyebrow">NEW LETTERS</span>
      <div className="letters-grid">{(letters.newLetters||[]).map(x=><button key={x.char} className={item?.char===x.char?"letter-tile active":"letter-tile"} onClick={()=>{setItem(x);setAnswer("")}}><strong>{x.char}</strong><small>{x.romaji}</small></button>)}</div>
      {!(letters.newLetters||[]).length&&<div className="review-note">No new symbols today — this is deliberate. Use today as a mastery checkpoint.</div>}
      <span className="eyebrow review-label">REVIEW SET</span>
      <div className="letters-grid compact">{(letters.reviewLetters||[]).map(x=><button key={x.char} className="letter-tile small" onClick={()=>{setItem(x);setAnswer("")}}><strong>{x.char}</strong><small>{x.romaji}</small></button>)}</div>
    </div>
   </div>
   <div className="script-checks"><span className="eyebrow">YOU MUST BE ABLE TO</span>{(letters.masteryChecks||[]).map((x,i)=><div key={x}><b>{i+1}</b><span>{x}</span></div>)}</div>
 </section>
}

function MasteryQuiz({lesson,onComplete}){
 const[q,setQ]=useState(0),[score,setScore]=useState(0),[picked,setPicked]=useState(null),item=lesson.quiz[q];
 if(!item)return <div className="panel"><h2>No quiz loaded</h2><button className="btn primary" onClick={()=>onComplete(100)}>Complete lesson</button></div>;
 function choose(i){if(picked!==null)return;setPicked(i);const n=score+(i===item.answer?1:0);setScore(n);setTimeout(()=>{if(q===lesson.quiz.length-1)onComplete(Math.round(n/lesson.quiz.length*100));else{setQ(q+1);setPicked(null)}},650)}
 return <section className="panel quiz-panel"><div className="quiz-top"><span className="eyebrow">MASTERY CHECK</span><b>{q+1}/{lesson.quiz.length}</b></div><div className="quiz-bar"><span style={{width:pct(q,lesson.quiz.length)*1+"%"}}/></div><h2>{item.question}</h2><div className="quiz-options">{item.options.map((o,i)=><button key={i} className={picked!==null?(i===item.answer?"correct":i===picked?"wrong":""):""} onClick={()=>choose(i)}>{String.fromCharCode(65+i)}<span>{o}</span></button>)}</div><p className="muted">Score 100% to unlock the next day.</p></section>
}

function Dashboard({completed,setDay,setView,user,onAuth,streak}){
 const next=Math.min(180,(completed.length?Math.max(...completed)+1:1)),progress=pct(completed.length,180),level=next<=90?"N5":"N4";
 return <div className="fade-in"><section className="hero"><div><span className="eyebrow">YOUR JAPANESE JOURNEY</span><h1>Read. Listen. Speak. <span>Master Japanese.</span></h1><p>You do not need to know a single Japanese letter to start. Michi teaches the script first, then builds reading, vocabulary, grammar, listening, speaking and JLPT skills in the right order.</p><div className="hero-actions"><button className="btn primary" onClick={()=>{setDay(next);setView("lesson")}}><Play size={15}/>Continue Day {next}</button>{!user&&<button className="btn secondary" onClick={()=>onAuth("register")}><LogIn size={15}/>Create free account</button>}</div></div><Tutor/></section>
 <div className="stats-grid"><Stat icon={<CalendarDays/>} value={completed.length+"/180"} label="Days mastered"/><Stat icon={<Flame/>} value={streak+" day"+(streak===1?"":"s")} label="Current streak"/><Stat icon={<Brain/>} value={level} label="Current level"/><Stat icon={<ShieldCheck/>} value={progress+"%"} label="Journey progress"/></div>
 <section className="section"><div className="section-title"><div><span className="eyebrow">{next<=15?"SCRIPT FOUNDATION":"TODAY"}</span><h2>{next<=15?"Learn the letters first":"Your next lesson"}</h2></div><button className="btn ghost" onClick={()=>setView("progress")}>View analytics <ChevronRight size={14}/></button></div><div className="today-card"><div className="today-number">{String(next).padStart(2,"0")}</div><div><span className="pill violet">{level} · DAY {next}</span><h3>{next===1?"Greetings, identity & your first Japanese sentences":"Continue your structured Japanese training"}</h3><p>Vocabulary · grammar · listening · speaking · reading · mastery</p></div><button className="btn primary" onClick={()=>{setDay(next);setView("lesson")}}>Start <ChevronRight size={15}/></button></div></section>
 <section className="section"><div className="section-title"><div><span className="eyebrow">YOUR CLEARANCE PATH</span><h2>What you need to clear the JLPT levels</h2><p>Michi uses practical target bands because JLPT does not publish one fixed official vocabulary/kanji list.</p></div></div><div className="clearance-grid"><div className="clearance-card"><span className="pill violet">N5 · DAYS 1–90</span><h3>Foundation → basic Japanese</h3><div><b>Script</b><span>100% hiragana + katakana + common sound changes</span></div><div><b>Kanji target</b><span>≈120 characters</span></div><div><b>Vocabulary target</b><span>≈1,000 high-frequency words</span></div><div><b>Exam skills</b><span>Vocabulary · Grammar · Reading · Listening</span></div></div><div className="clearance-card"><span className="pill">N4 · DAYS 91–180</span><h3>Connected everyday Japanese</h3><div><b>Script</b><span>Fast kana + common kanji compounds</span></div><div><b>Kanji target</b><span>≈300 cumulative characters</span></div><div><b>Vocabulary target</b><span>≈2,000 cumulative words</span></div><div><b>Exam skills</b><span>Longer reading · grammar · listening</span></div></div></div></section> <section className="section"><div className="section-title"><div><span className="eyebrow">YOUR TOOLKIT</span><h2>Train every Japanese skill</h2></div></div><div className="feature-grid">{[["kana","Kana Lab","Master hiragana & katakana",<Languages/>],["review","Review","Spaced recall before you forget",<RefreshCw/>],["speaking","Speaking","Pronunciation + speech feedback",<Mic/>],["mock","JLPT Mock","Timed N5/N4 exam simulation",<Target/>]].map(x=><button className="feature-card" key={x[0]} onClick={()=>setView(x[0])}><div>{x[3]}</div><h3>{x[1]}</h3><p>{x[2]}</p><ChevronRight size={15}/></button>)}</div></section>
 <section className="section"><div className="section-title"><div><span className="eyebrow">180-DAY PATH</span><h2>N5 → N4 curriculum</h2><p>Mastery unlocks the next day.</p></div></div><Curriculum completed={completed} currentDay={next} onSelect={d=>{setDay(d);setView("lesson")}}/></section></div>
}

function Curriculum({completed,currentDay,onSelect}){
 const[level,setLevel]=useState("N5"),start=level==="N5"?1:91,names=level==="N5"?["Foundations","Daily life","People & places","Time","Food","Movement","Review","Home & study","Adjectives","Past","Requests","Experience","N5 review"]:["Routines","Plans","Comparisons","Health","Travel","Work & school","Review","Opinions","Ability","Rules","Conditions","Connected speech","N4 review"];
 const weeks=Array.from({length:13},(_,i)=>{const first=start+i*7,last=Math.min(first+6,start+89);return{first,last,days:Array.from({length:last-first+1},(_,j)=>first+j),name:names[i]}});
 return <div><div className="tabs"><button className={level==="N5"?"active":""} onClick={()=>setLevel("N5")}>N5 Foundation</button><button className={level==="N4"?"active":""} onClick={()=>setLevel("N4")}>N4 Elementary</button></div><div className="week-grid">{weeks.map((w,i)=>{const unlocked=w.first===1||completed.includes(w.first-1),done=w.days.every(d=>completed.includes(d));return <button key={w.first} disabled={!unlocked} className={"week-card "+(!unlocked?"locked":"")} onClick={()=>onSelect(w.days.find(d=>!completed.includes(d))||w.first)}><div><small>WEEK {i+1}</small><span>{done?<CheckCircle2 size={14}/>:unlocked?<ChevronRight size={14}/>:<Lock size={13}/>}</span></div><h3>{w.name}</h3><p>Days {w.first}–{w.last}</p><div className="day-strip">{w.days.map(d=><i key={d} className={completed.includes(d)?"done":d===currentDay?"current":""}>{d}</i>)}</div></button>})}</div></div>
}

function Review({completed,onComplete}){
 const words=useMemo(()=>{const all=[];for(let d=1;d<=Math.min(7,Math.max(1,completed.length+1));d++){const l=localLesson(d);l.vocab.forEach(v=>all.push({...v,day:d}))}return all.slice(0,30)},[completed]);
 const[index,setIndex]=useState(0),[show,setShow]=useState(false),[known,setKnown]=useState(0),w=words[index%Math.max(1,words.length)];
 if(!w)return <Empty title="Your review queue is empty" text="Complete a lesson and Michi will start building your recall queue." />;
 return <div className="fade-in"><PageTitle eyebrow="SPACED REVIEW" title="Review before you forget" text="Active recall beats rereading. Reveal the answer, grade yourself, and keep moving."/><div className="review-card"><div className="review-count">CARD {index+1} / {words.length}</div><div className="review-char">{w.ja}</div>{show?<><div className="review-romaji">{w.romaji}</div><div className="review-meaning">{w.en}</div><Audio text={w.ja}/><div className="review-actions"><button className="btn secondary" onClick={()=>{setShow(false);setIndex(index+1)}}>Again</button><button className="btn primary" onClick={()=>{setKnown(known+1);setShow(false);setIndex(index+1)}}><Check size={15}/>I knew it</button></div></>:<button className="btn primary" onClick={()=>setShow(true)}>Reveal answer</button>}</div><div className="review-footer"><span>{known} recalled</span><div className="bar"><span style={{width:pct(known,Math.max(1,index))+"%"}}/></div></div></div>
}
function KanaLab(){
 const[type,setType]=useState("hiragana"),[mode,setMode]=useState("recognize"),[i,setI]=useState(0),[answer,setAnswer]=useState(""),[score,setScore]=useState(0);const set=type==="hiragana"?HIRA:KATA,item=set[i%set.length];
 function next(){setAnswer("");setI(i+1)}
 function check(){if(answer.trim().toLowerCase()===item[1])setScore(score+1);next()}
 return <div className="fade-in"><PageTitle eyebrow="KANA LAB" title="Read Japanese scripts" text="Master hiragana first, then katakana. Recognition comes before speed."/><div className="lab-tabs"><button className={type==="hiragana"?"active":""} onClick={()=>{setType("hiragana");next()}}>ひ Hiragana</button><button className={type==="katakana"?"active":""} onClick={()=>{setType("katakana");next()}}>カ Katakana</button></div><div className="kana-layout"><section className="panel kana-practice"><span className="eyebrow">{mode==="recognize"?"RECOGNITION":"MEMORY"}</span><div className="kana-big">{item[0]}</div><p>What sound is this?</p><input autoFocus value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>e.key==="Enter"&&check()} placeholder="Type romaji…" /><button className="btn primary" onClick={check}>Check</button><div className="lab-score">{score} correct</div></section><section className="panel"><span className="eyebrow">REFERENCE</span><h2>{type==="hiragana"?"Hiragana":"Katakana"} chart</h2><div className="kana-grid">{set.map(x=><button key={x[0]} className={x[0]===item[0]?"selected":""} onClick={()=>{setI(set.indexOf(x));setAnswer("")}}><strong>{x[0]}</strong><small>{x[1]}</small></button>)}</div></section></div></div>
}
function KanjiLab(){const[start,setStart]=useState(0),items=KANJI.slice(start,start+8);return <div className="fade-in"><PageTitle eyebrow="KANJI LAB" title="Build your N5 → N4 character bank" text="Learn meaning and readings together. Say every character aloud."/><div className="kanji-lab-grid">{items.map(k=><div className="kanji-card large" key={k[0]}><strong>{k[0]}</strong><span>{k[1]}</span><small>{k[2]}</small><button onClick={()=>speak(k[0])}><Volume2 size={14}/> Listen</button></div>)}</div><div className="center-actions"><button className="btn secondary" disabled={start===0} onClick={()=>setStart(Math.max(0,start-8))}>Previous</button><button className="btn primary" disabled={start+8>=KANJI.length} onClick={()=>setStart(start+8)}>Next characters</button></div></div>}
function SpeakingLab(){const examples=[...week1.flatMap(d=>d.examples||[]).map(x=>Array.isArray(x)?x[0]:x.ja)].slice(0,12);const[target,setTarget]=useState(examples[0]||"こんにちは。"),[busy,setBusy]=useState(false),[heard,setHeard]=useState(""),[score,setScore]=useState(null);function run(){setBusy(true);listenOnce({onResult:t=>{setHeard(t);setScore(Math.round(similarity(t,target)*100))},onError:e=>setHeard(e==="not-allowed"?"Microphone permission denied.":String(e)),onEnd:()=>setBusy(false)})}return <div className="fade-in"><PageTitle eyebrow="SPEAKING LAB" title="Make your Japanese audible" text="Use the browser microphone to compare your spoken Japanese with a target phrase."/><div className="speaking-layout"><section className="panel"><span className="eyebrow">TARGET PHRASE</span><div className="speak-target-big">{target}</div><Audio text={target}/><button className={"speak-button "+(busy?"recording":"")} onClick={run}><Mic size={22}/>{busy?"Listening…":"Speak now"}</button>{heard&&<div className="speech-result"><span>You said</span><strong>{heard}</strong><em>{score}% match</em></div>}{!speechRecognitionSupported()&&<div className="callout warning">Speech recognition is unavailable in this browser. Try Chrome or Edge.</div>}</section><section className="panel"><span className="eyebrow">PHRASE BANK</span><div className="phrase-list">{examples.map(x=><button key={x} className={x===target?"active":""} onClick={()=>{setTarget(x);setHeard("");setScore(null)}}>{x}<Volume2 size={14}/></button>)}</div></section></div></div>}
function MockExam({level="N5"}){
 const bank=useMemo(()=>{const l=localLesson(level==="N5"?1:91);return l.quiz.length?l.quiz:makeQuiz(l.vocab)},[level]),[q,setQ]=useState(0),[score,setScore]=useState(0),[selected,setSelected]=useState(null),[done,setDone]=useState(false),item=bank[q%bank.length];
 function choose(i){if(selected!==null)return;setSelected(i);const n=score+(i===item.answer?1:0);setScore(n);setTimeout(()=>{if(q===bank.length-1)setDone(true);else{setQ(q+1);setSelected(null)}},450)}
 if(done)return <div className="result-card"><Trophy size={42}/><span className="eyebrow">MOCK EXAM COMPLETE</span><h1>{Math.round(score/bank.length*100)}%</h1><p>{score} / {bank.length} correct</p><button className="btn primary" onClick={()=>{setQ(0);setScore(0);setSelected(null);setDone(false)}}><RotateCcw size={15}/> Retake</button></div>;
 return <div className="fade-in"><PageTitle eyebrow="JLPT MOCK EXAM" title={level+" practice test"} text="Timed-style practice. This prototype uses your loaded curriculum; expand the bank as the curriculum grows."/><div className="exam-head"><div><span>Question {q+1}/{bank.length}</span><b>{score} correct</b></div><div className="exam-progress"><span style={{width:pct(q,bank.length)+"%"}}/></div></div><section className="panel exam-question"><span className="eyebrow">LANGUAGE KNOWLEDGE</span><h2>{item.question}</h2><div className="quiz-options">{item.options.map((o,i)=><button key={i} className={selected!==null?(i===item.answer?"correct":i===selected?"wrong":""):""} onClick={()=>choose(i)}>{String.fromCharCode(65+i)}<span>{o}</span></button>)}</div></section></div>
}
function Progress({completed,streak}){const progress=pct(completed.length,180),days=Math.max(1,completed.length),rate=Math.round(completed.length/days*100),ach=[completed.length>=1&&["First Step","Completed your first day","1 day"],completed.length>=7&&["Week One","Mastered seven days","7 days"],completed.length>=30&&["Month Strong","Mastered thirty days","30 days"],streak>=7&&["On Fire","Seven-day streak","7 days"],completed.length>=90&&["N5 Ready","Completed N5","90 days"]].filter(Boolean);return <div className="fade-in"><PageTitle eyebrow="PROGRESS" title="Your learning analytics" text="See the habits that are moving you forward."/><div className="stats-grid"><Stat icon={<Target/>} value={progress+"%"} label="Course progress"/><Stat icon={<Check/>} value={completed.length} label="Days mastered"/><Stat icon={<Flame/>} value={streak} label="Day streak"/><Stat icon={<Trophy/>} value={ach.length} label="Achievements"/></div><div className="analytics-grid"><section className="panel"><span className="eyebrow">JOURNEY</span><h2>N5 → N4</h2><div className="big-progress"><span style={{width:progress+"%"}}/></div><div className="split-stat"><span>N5 <b>{Math.min(90,completed.length)}/90</b></span><span>N4 <b>{Math.max(0,completed.length-90)}/90</b></span></div></section><section className="panel"><span className="eyebrow">ACHIEVEMENTS</span><div className="achievement-list">{ach.length?ach.map(a=><div key={a[0]}><div className="achievement-icon"><Trophy size={16}/></div><div><b>{a[0]}</b><small>{a[1]}</small></div><span>{a[2]}</span></div>):<p className="muted">Complete your first lesson to unlock achievements.</p>}</div></section></div></div>}
function PageTitle({eyebrow,title,text}){return <div className="page-title"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{text}</p></div>}
function Empty({title,text}){return <div className="empty panel"><Sparkles size={30}/><h2>{title}</h2><p>{text}</p></div>}
function SettingsView({user,onAuth}){const[auto,setAuto]=useState(localStorage.getItem("michiAutoAudio")==="1"),[daily,setDaily]=useState(localStorage.getItem("michiDaily")!=="0");function toggle(k,v){localStorage.setItem(k,v?"1":"0");}return <div className="fade-in"><PageTitle eyebrow="SETTINGS" title="Make Michi yours" text="Control your study experience on this device."/><section className="panel settings-panel"><div className="setting-row"><div><b>Account</b><small>{user?user.email:"Guest mode — progress stays on this device"}</small></div>{user?<button className="btn secondary" onClick={logout}><LogOut size={14}/>Sign out</button>:<button className="btn primary" onClick={()=>onAuth("login")}><LogIn size={14}/>Sign in</button>}</div><div className="setting-row"><div><b>Auto audio</b><small>Speak Japanese automatically when opening a word.</small></div><button className={"toggle "+(auto?"on":"")} onClick={()=>{setAuto(!auto);toggle("michiAutoAudio",!auto)}}><i/></button></div><div className="setting-row"><div><b>Daily goal</b><small>Keep the 10–15 minute daily study target visible.</small></div><button className={"toggle "+(daily?"on":"")} onClick={()=>{setDaily(!daily);toggle("michiDaily",!daily)}}><i/></button></div><div className="setting-row"><div><b>Keyboard shortcuts</b><small>Enter submits recall answers. Space can trigger audio in future modules.</small></div><Keyboard size={19}/></div></section></div>}

export default function App(){
 const[completed,setCompleted]=useState(()=>{try{return JSON.parse(localStorage.getItem("jlptProgress")||"[]")}catch{return[]}}),[user,setUser]=useState(null),[view,setView]=useState("dashboard"),[day,setDay]=useState(1),[lesson,setLesson]=useState(null),[auth,setAuth]=useState(null),[sidebar,setSidebar]=useState(false),[streak,setStreak]=useState(calcStreak(getStreak()));
 useEffect(()=>watchAuth(async u=>{setUser(u);if(u){try{const p=await loadProgress(u.uid);if(p.length){setCompleted(p);localStorage.setItem("jlptProgress",JSON.stringify(p))}}catch{}}}),[]);
 useEffect(()=>{if(view!=="lesson")return;let alive=true;const local=localLesson(day);setLesson(local);if(day>7)loadLesson(day).then(x=>{if(alive&&x)setLesson(normalizeLesson(x,day))}).catch(()=>{});return()=>{alive=false}},[day,view]);
 function go(v){setView(v);setSidebar(false);setStreak(calcStreak(markActivity()))}
 async function complete(score){markActivity();setStreak(calcStreak(getStreak()));if(score===100&&!completed.includes(day)){const n=[...completed,day].sort((a,b)=>a-b);setCompleted(n);localStorage.setItem("jlptProgress",JSON.stringify(n));if(user){await saveProgress(user.uid,n);await saveAttempt(user.uid,day,score)}}else if(user)await saveAttempt(user.uid,day,score);setView("dashboard")}
 const next=Math.min(180,completed.length?Math.max(...completed)+1:1);
 const nav=[["dashboard","Dashboard",<Home/>],["lesson","Learn today",<BookOpen/>],["review","Review",<RefreshCw/>],["kana","Kana Lab",<Languages/>],["kanji","Kanji Lab",<Brain/>],["speaking","Speaking",<Mic/>],["mock","JLPT Mock",<Target/>],["progress","Progress",<BarChart3/>]];
 return <div className="app">{sidebar&&<div className="mobile-overlay" onClick={()=>setSidebar(false)}/>}<aside className={"sidebar "+(sidebar?"open":"")}><div className="brand"><div className="logo-mark">道</div><div><b>Michi <span>みち</span></b><small>Your path to Japanese</small></div></div><div className="nav-caption">LEARN</div>{nav.slice(0,7).map(([id,label,icon])=><button key={id} className={view===id?"nav-item active":"nav-item"} onClick={()=>{if(id==="lesson")setDay(next);go(id)}}>{icon}<span>{label}</span>{id==="review"&&completed.length>0?<em>NEW</em>:null}</button>)}<div className="nav-caption">ACCOUNT</div><button className="nav-item" onClick={()=>user?logout():setAuth("login")}>{user?<LogOut/>:<CircleUserRound/>}<span>{user?"Sign out":"Sign in"}</span></button><button className={"nav-item "+(view==="settings"?"active":"")} onClick={()=>go("settings")}><Settings/><span>Settings</span></button><div className="sidebar-bottom"><div className="streak-mini"><Flame size={17}/><div><b>{streak} day streak</b><small>Keep your path alive.</small></div></div><div className="mini-bar"><span style={{width:pct(completed.length,180)+"%"}}/></div><small>{completed.length}/180 mastered</small></div></aside>
 <div className="shell"><header className="topbar"><button className="mobile-menu" onClick={()=>setSidebar(true)}><Menu/></button><div className="top-context">{view==="dashboard"?"Dashboard":view==="lesson"?"Lesson workspace":view.replace("mock","JLPT Mock").replace("kana","Kana Lab")}</div><div className="top-actions">{streak>0&&<span className="top-streak"><Flame size={14}/>{streak}</span>}{user?<div className="user-chip"><span>{(user.email||"M")[0].toUpperCase()}</span>{user.email}</div>:<><button className="btn ghost" onClick={()=>setAuth("login")}>Sign in</button><button className="btn primary" onClick={()=>setAuth("register")}>Create account</button></>}</div></header>
 <main className="main">{view==="dashboard"&&<Dashboard completed={completed} setDay={setDay} setView={go} user={user} onAuth={setAuth} streak={streak}/>}
 {view==="lesson"&&(lesson?<Lesson lesson={lesson} day={day} onBack={()=>go("dashboard")} onComplete={complete}/>:<div className="panel loading">Preparing Day {day}…</div>)}
 {view==="review"&&<Review completed={completed}/>}
 {view==="kana"&&<KanaLab/>}{view==="kanji"&&<KanjiLab/>}{view==="speaking"&&<SpeakingLab/>}{view==="mock"&&<MockExam/>}{view==="progress"&&<Progress completed={completed} streak={streak}/>}
 {view==="settings"&&<SettingsView user={user} onAuth={setAuth}/>}</main></div>{auth&&<AuthModal mode={auth} setMode={setAuth} onClose={()=>setAuth(null)}/>}</div>
}
